add service account permission list widget
JupiterOne/insights-dashboards pull request #42
Opened 2022-04-15 21:03 UTC by jacob-dowdy

add GCP service account permission list widget and layout

2022-04-18 14:21 UTC, ericanagle1 approved these changes

2022-04-18 14:21 UTC, a-u-h-g requested changes
Can you also add an updated screenshot?

2022-04-18 15:11 UTC, a-u-h-g submitted a review, later dismissed

2022-04-18 15:25 UTC, jacob-dowdy commented
Added updated board pic and widget layout

2022-05-11 23:26 UTC, erkangz commented on src/boards/gcp-iam/board.json
> -				"i": "18b673fb-c504-4aa8-9073-9a21997dda8e",
Are these intentionally deleted?

2022-05-13 18:01 UTC, erkangz requested changes

2022-05-13 18:01 UTC, erkangz commented on src/boards/gcp-iam/board.json
> +						"query": "Find google_iam_service_account with tag.AccountName = 'sysdig-development-2' as user\n  that assigned google_iam_binding\n  that uses google_iam_role with readonly!=true\nreturn tree
is this `with tag.AccountName = 'sysdig-development-2'` hardcoded filter intentional?

2022-05-13 18:01 UTC, erkangz commented on src/boards/gcp-iam/board.json
> +						"query": "Find google_user with _source = 'system-mapper'\n  that assigned google_iam_binding with tag.AccountName = 'datadog-dev-335212'\n  that uses google_iam_role with readonly!=true \n  re
Same here - AccountName filter intentional?

2022-06-06 10:23 UTC, closed without merging