cloud-instance-workload-analysis-dashboard
JupiterOne/insights-dashboards pull request #57
Opened 2022-05-11 22:23 UTC by ericanagle1

2022-05-11 23:24 UTC, erkangz requested changes

2022-05-11 23:24 UTC, erkangz commented on src/boards/cloud-instance-workload-analysis/readme.md
> +Enter hostname, instanceId or ipAddress to visualize all the resources related to a compromised host/workload/instance. Review the privileged access to the instance and view the blast radius — in the
We should update this description a bit. 

The board answers 5 key questions for any given virtual instance or workload across all 3 major CSPs in seconds:

- What resources are connected to it?
- What else are in the same blast radius?
- How is it connected to the Internet (external attack path)?
- Who has admin / privileged access to it?
- What data stores does it have access to?

2022-05-12 00:14 UTC, ericanagle1 reviewed
Adjustment made on description

2022-05-12 00:55 UTC, erkangz commented on src/boards/cloud-instance-workload-analysis/readme.md
> +This board answers 5 key questions for any given virtual instance or workload across all 3 major CSPs in seconds:
```suggestion
This is an interactive dashboard that will prompt you to enter the hostname or IP address or instance ID of a cloud workload / instance.

This board answers 5 key questions for any given virtual instance or workload across all 3 major CSPs in seconds:
```

2022-05-12 00:56 UTC, erkangz commented on src/boards/cloud-instance-workload-analysis/readme.md
> +What data stores does it have access to?
```suggestion
- Is the workload / instance still active or online? What are its configurations?
- What resources are connected to it?
- What else are in the same blast radius?
- How is it connected to the Internet (external attack path)?
- Who has admin / privileged access to it?
- What data stores does it have access to?
```

2022-05-12 00:57 UTC, erkangz approved these changes

2022-05-12 19:44 UTC, BrendanQuinnJ1 approved these changes
Approved

2022-05-12 19:50 UTC, merged