add-user-endpoint-blast-radius-dashboard
JupiterOne/insights-dashboards pull request #58
Opened 2022-05-11 22:35 UTC by ericanagle1

2022-05-11 23:22 UTC, erkangz requested changes

2022-05-11 23:22 UTC, erkangz commented on src/boards/user-endpoint-blast-radius/readme.md
> +Enter a variable such as an ipAddress to visualize a device owners access, full inventory of digital identities, and resource allocation.
This board is limited to the macAddress of a device.

2022-05-11 23:22 UTC, erkangz commented on src/boards/user-endpoint-blast-radius/readme.md
> +> This works best when integrations to different providers and accounts are
As many as possible related to user endpoint agents and SaaS applications.

2022-05-12 00:08 UTC, ericanagle1 commented on src/boards/user-endpoint-blast-radius/readme.md
> +Enter a variable such as an ipAddress to visualize a device owners access, full inventory of digital identities, and resource allocation.
adjusted

2022-05-12 00:08 UTC, ericanagle1 commented on src/boards/user-endpoint-blast-radius/readme.md
> +> This works best when integrations to different providers and accounts are
adjusted

2022-05-12 00:09 UTC, ericanagle1 reviewed
Adjustments made

2022-05-12 00:53 UTC, erkangz commented on src/boards/user-endpoint-blast-radius/readme.md
> +Enter a macAddress of a device and visualize the device owners access, full inventory of digital identities, and resource allocation.
```suggestion
This is an interactive dashboard that will prompt you to enter a macAddress of a device and visualize the device owner's access, full inventory of digital identities, and the resources they have access to.  
```

2022-05-12 00:53 UTC, erkangz approved these changes

2022-05-12 19:44 UTC, BrendanQuinnJ1 approved these changes
Approved

2022-05-12 19:50 UTC, merged