add-team-peers-manager-direct-reports-dashboard
JupiterOne/insights-dashboards pull request #59
Opened 2022-05-11 22:47 UTC by ericanagle1

2022-05-11 23:20 UTC, erkangz requested changes
The board image isn't great with all the blocked out display names. Is there another way?

2022-05-11 23:20 UTC, erkangz commented on src/boards/team-manager-direct-reports/readme.md
> +> An integration to an identity provider or directory service, such as Okta, Azure AD, JumpCloud.
We should include Google Workspace. Also, the identity provider must be configured with directory services with data related to people management. 

We should also include HRIS integrations such as BambooHR.

2022-05-11 23:20 UTC, erkangz commented on src/boards/team-manager-direct-reports/readme.md
> +Type in a managers email and gather data on their direct reports, what team members and peers they have along with their directs information.
Not manager's email. An individual's email to get the person's peers/team members, manager, and direct reports (if there is any).

2022-05-11 23:59 UTC, ericanagle1 commented on src/boards/team-manager-direct-reports/readme.md
> +Type in a managers email and gather data on their direct reports, what team members and peers they have along with their directs information.
Just updated description

2022-05-11 23:59 UTC, ericanagle1 commented on src/boards/team-manager-direct-reports/readme.md
> +> An integration to an identity provider or directory service, such as Okta, Azure AD, JumpCloud.
Let me know if what I changed works a little better

2022-05-12 00:03 UTC, ericanagle1 commented on src/boards/team-manager-direct-reports/readme.md
> +> An integration to an identity provider or directory service, such as Okta, Azure AD, JumpCloud.
Also for the board image - I completely agree. The only other thing I could think of was if I could add the dashboard to the play instance because I think that has user data but I'm not positive

2022-05-12 00:50 UTC, erkangz commented on src/boards/team-manager-direct-reports/readme.md
> +Type an individual's email to get the person's peers/team members, manager, and direct reports.
```suggestion
This is an interactive dashboard that will prompt you to enter an individual's email to get the person's peers/team members, manager, and direct reports.
```

2022-05-12 00:50 UTC, erkangz approved these changes

2022-05-12 19:43 UTC, BrendanQuinnJ1 commented
I accept

2022-05-12 19:44 UTC, BrendanQuinnJ1 approved these changes
Approved

2022-05-12 19:50 UTC, merged