update-readme-with-new-dashboards-added
JupiterOne/insights-dashboards pull request #62
Opened 2022-05-13 16:01 UTC by ericanagle1

2022-05-13 17:59 UTC, erkangz requested changes

2022-05-13 17:59 UTC, erkangz commented on README.md
> +- [User Endpoint Blast Radius](src/boards/user-endpoint-blast-radius/)
let's prefix this with "IR"

2022-05-13 17:59 UTC, erkangz commented on README.md
> +- [Cloud Instance & Workload Analysis](src/boards/cloud-instance-workload-analysis)
let's prefix this with "IR" and move next to the other IR dashboard because they are of the same use case.

2022-05-13 18:19 UTC, ericanagle1 reviewed
Updated titles for IR dashboards

2022-05-13 19:02 UTC, erkangz commented on README.md
> +- [Team Management and Direct Repors](src/boards/team-manager-direct-reports/)
```suggestion
- [Team, Manager and Direct Reports](src/boards/team-manager-direct-reports/)
```

2022-05-17 21:53 UTC, ericanagle1 reviewed
Let me know if this looks a little better

2022-05-17 22:13 UTC, DrewJohnsonGT approved these changes

2022-05-18 01:08 UTC, erkangz approved these changes

2022-05-18 01:08 UTC, merged